// DO NOT EDIT THIS FILE
#pragma once

#include "TreeNode.h"

// Q5.A
std::string suggestWordV1(TreeNode<char>* dict, std::string word);

// Q5.B
std::string suggestWordV2(TreeNode<char>* dict, std::string word);

// Q6
int findTreeDiameter(TreeNode<int>* root);
